name: Pylint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    
    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}
     
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord
        pip install python-dotenv
        pip install pylint
        
    - name: Analysing the code with pylint
      run: |
        python -m pylint --fail-under=2 "find -regextype egrep -regex '(.*.py)$'"
        - if: failure()
          run: echo "Failure"
